/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  cursoSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Nivel I: Fundamentos',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'nivel-1-fundamentos',
        },
      ],
    },
    {
      type: 'category',
      label: 'Nivel II: Configuración y Extensibilidad',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'nivel-2-configuracion-extensibilidad',
        },
      ],
    },
    {
      type: 'category',
      label: 'Nivel III: Orquestación y Escalado',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'nivel-3-orquestacion-escalado',
        },
      ],
    },
    {
      type: 'category',
      label: 'Nivel IV: Producción y Gobernanza',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'nivel-4-produccion-gobernanza',
        },
      ],
    },
    {
      type: 'category',
      label: 'Laboratorios',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'laboratorios',
        },
      ],
    },
    {
      type: 'category',
      label: 'Referencias',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'referencias',
        },
      ],
    },
  ],
};

module.exports = sidebars;
